name: Zensation
favicon: null
layout_spectrum: 0.6489841262809932
typography_spectrum: 0.7033349988050759
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.008783725323155522
  lightness: 0.5198290406260639
  saturation: 0.6946351618971676
  rhythmicContrast: 0.043171317083761096
purpose: []
